FROM golang:1.24 as build

WORKDIR /build

COPY go.mod go.sum .

RUN go mod download

COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 go build -ldflags "-w -s" ./cmd/server

FROM alpine:3 as run

RUN apk add --no-cache \
    ca-certificates

WORKDIR /app

VOLUME /app/pb_data

COPY --from=build /build/server ./

EXPOSE 8080

CMD ["./server", "serve", "--http=0.0.0.0:8080"]

