name: Build and Push Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and Push Multi-Arch Image'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfile
          push: true
          tags: ghcr.io/t-muehlberger/pb-starter:latest
          platforms: linux/amd64,linux/arm64
